resolver: lts-11.7

packages:
- '.'

extra-deps:
- network-transport-inmemory-0.5.1  # snapshot 0.5.2 in lts-7.18
- distributed-process-0.7.3         # missing snapshot
- rematch-0.2.0.0
- distributed-process-extras-0.3.4
- distributed-process-async-0.2.5
