resolver: nightly-2017-08-20

packages:
- '.'
- location:
    git: https://github.com/haskell-distributed/distributed-process-systest.git
    commit: b4a6b646adb6c81725ddac4babcfc21b86944d98
  extra-dep: true

extra-deps:
- ansi-terminal-0.6.3.1
- network-transport-0.5.2
- network-transport-tcp-0.6.0
- network-transport-inmemory-0.5.2
- distributed-process-0.7.4         # missing snapshot
- rematch-0.2.0.0
- distributed-process-extras-0.3.5
- distributed-process-async-0.2.6
- exceptions-0.10.0
- rank1dynamic-0.4.0
- distributed-static-0.3.8
- distributed-process-client-server-0.2.5.1
