name: Continuous integration with stack
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghcVersion:
          [ "8.10.7"
          , "9.0.2"
          , "9.2.7"
          , "9.4.5"
          , "9.8.2"
          ]
    container: "fpco/stack-build-small"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cache stack dependencies
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/stack-root
          key: cache-key-${{ runner.os }}-${{ hashFiles(format('stack-ghc-{0}.yaml', matrix.ghcVersion)) }}
      - shell: bash
        name: run tests
        run: |
          set -ex
          chown $(whoami) "$GITHUB_WORKSPACE"
          export STACK_ROOT="$GITHUB_WORKSPACE/stack-root"
          export ARGS="--stack-yaml stack-ghc-${{ matrix.ghcVersion }}.yaml"
          export ARG='--test-arguments'
          export TEST_PACKAGE="distributed-process-tests:"
          stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestCHInMemory
          stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestCHInTCP
          stack ${ARGS} test $ARG='--plain -t "!SpawnReconnect"' ${TEST_PACKAGE}TestClosure
          stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestStats
          stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestMxInMemory
          stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestMxInTCP
          stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestTracingInMemory
